### ISSUE TITLE
openocd is already existing...

### ISSUE THREAD

**Issue by karlp** [esden/summon-arm-toolchain#13]
---
- Cloning OpenOCD sources...
  ******************************************************************
  Cloning into openocd-master...
  remote: Counting objects: 38873, done.
  remote: Compressing objects: 100% (8792/8792), done.
  remote: Total 38873 (delta 32027), reused 36741 (delta 29965)
  Receiving objects: 100% (38873/38873), 8.48 MiB | 769 KiB/s, done.
  Resolving deltas: 100% (32027/32027), done.
- aclocal
  ./bootstrap: 1: aclocal: not found
  karlp@dragnet:~/src/summon-arm-toolchain$ sudo apt-get build-essential gcc gdb
  [sudo] password for karlp: 
  E: Invalid operation build-essential
  karlp@dragnet:~/src/summon-arm-toolchain$

From here, I installed autoconf and tried again.... However, restarting the "summon-arm-toolchain" failed again, when it found that openocd had already been git cloned out....

---
- Cloning OpenOCD sources...
  ******************************************************************
  fatal: destination path 'openocd-master' already exists and is not an empty directory.
  karlp@dragnet:~/src/summon-arm-toolchain$

Perhaps it should just try and execute a git check in the directory?  or just trample? this is just the build directory right?

It works again after simply "rm -rf sources/openocd-master/"

**Comment by esden** [comment]
I am working on a better way of handling git repositories in SAT. It will beside many others also take care of doing sanity checks that will prevent such errors.
