### ISSUE TITLE
hardfloat - support?

### ISSUE THREAD

**Issue by thomask77** [esden/summon-arm-toolchain#14]
Hi!

Is there any support for -mfloat-abi=hard yet?

This would be a real killer feature for SAT, because the free version of the commercial toolchains always omit this calling convention. There are also cheap STM32F4 discovery boards which would really benefit from that.

**Comment by jeremyherbert** [comment]
I have been trying to get this working (unsuccessfully) over the last few days also. +1

**Comment by esden** [comment]
I know that this is a broadly requested feature. I sadly did not have time till now to take a look into that, and I am not sure when I will. :(

**Comment by jeremyherbert** [comment]
I have had success using the hard floating point unit with MikeSmith's fork of this project.

https://github.com/MikeSmith/summon-arm-toolchain

for the record, the flags you should use are:

-mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mlittle-endian

**Comment by soonhooi** [comment]
I tried to compile summon-arm-toolchain in windows with Git Bash; but encounter the "Found unknown OS. Aborting!" error after running ./summon-arm-toolchain. 

Is there a workaround for this? Thanks!

**Comment by prattmic** [comment]
I managed to get a working hardfloat toolchain, though I have heard from some that they are unable to get it to build.

https://github.com/prattmic/arm-cortex-m4-hardfloat-toolchain

**Comment by thomask77** [comment]
Since some time, there's also an official(?) toolchain from ARM(?) with hardfloat-multilibs:

  https://launchpad.net/gcc-arm-embedded

I'm using it for all my new projects, replacing the CodeSourcery toolchain.

**Comment by esden** [comment]
Hardfloat should be working now. Please open a new issue if this still persists. :)
