### ISSUE TITLE
error compiling libopencm3

### ISSUE THREAD

**Issue by uglyoldbob** [esden/summon-arm-toolchain#16]
Not sure what to do about this.

---
- Building libopencm3-c49f505df4205e166a184de8063eb1702813cf46
  ******************************************************************
  BUILD   lib/stm32/f1
  CC      vector.o
  CC      rcc.o
  CC      gpio.o
  CC      usart.o
  CC      adc.o
  CC      spi.o
  ../spi.c: In function 'spi_reset':
  ../spi.c:39:3: warning: implicit declaration of function 'rcc_peripheral_reset'
  ../spi.c:39:25: error: 'RCC_APB2RSTR' undeclared (first use in this function)
  ../spi.c:39:25: note: each undeclared identifier is reported only once for each function it appears in
  ../spi.c:39:39: error: 'RCC_APB2RSTR_SPI1RST' undeclared (first use in this function)
  ../spi.c:40:3: warning: implicit declaration of function 'rcc_peripheral_clear_reset'
  ../spi.c:43:25: error: 'RCC_APB1RSTR' undeclared (first use in this function)
  ../spi.c:43:39: error: 'RCC_APB2RSTR_SPI2RST' undeclared (first use in this function)
  ../spi.c:47:39: error: 'RCC_APB2RSTR_SPI3RST' undeclared (first use in this function)
  make[1]: **\* [spi.o] Error 1
  make: **\* [lib] Error 2

**Comment by esden** [comment]
Thanks for reporting that! Solved in the latest revision of libopencm3, please try again.

**Comment by uglyoldbob** [comment]
That solved the issue. Thanks for the quick fix.
