### ISSUE TITLE
Problem building with automake 1.11.2+

### ISSUE THREAD

**Issue by makapuf** [esden/summon-arm-toolchain#22]
using Ubuntu 12.04, I have a problem compiling : 

```
******************************************************************
* Cloning oocd-9e1a16690e669b895dce7c3951b1fe893bfd6149 ...
******************************************************************
Cloning into 'oocd-9e1a16690e669b895dce7c3951b1fe893bfd6149'...
[...]
Switched to a new branch 'sat-branch'
[...]
doc/Makefile.am:1: installing `doc/mdate-sh'
doc/Makefile.am:1: installing `doc/texinfo.tex'
src/Makefile.am: installing `./depcomp'
src/jtag/drivers/Makefile.am:8: `pkglibdir' is not a legitimate directory for `DATA'
src/target/Makefile.am:166: `pkglibdir' is not a legitimate directory for `DATA'
Makefile.am: installing `./INSTALL'
```

It seems to come from an incompatibility with auto make version 1.11.3 : 

```
    automake --version 
    automake (GNU automake) 1.11.3
```

which seem to have problems with oocd as stated here : http://www.digipedia.pl/usenet/thread/11629/19775/
a patch seem to be defined here : http://openocd.zylin.com/#/c/457/

however, I'm a little lost as what to do from there ...

**Comment by langwadt** [comment]
I'm trying on cygwin, I rolled back to automake 1.11.1 and it seems to be working

**Comment by makapuf** [comment]
yes, I think there is a problem starting with automake 1.11.2

**Comment by makapuf** [comment]
in fact, this has already been fixed in a branch : https://github.com/agschult/summon-arm-toolchain/tree/

**Comment by josepharmbruster** [comment]
For reference, one workaround for this is to use automake 1.10.

**Comment by esden** [comment]
I think it should be working now. Please open a new issue if the problem still persists. :)
