### ISSUE TITLE
Requirements for gcc building. 

### ISSUE THREAD

**Issue by rewolff** [esden/summon-arm-toolchain#25]
Only after a time-consuming unpacking of gcc does the script recognize that the requirements for gcc-building are not met. 

In my case several libraries that have to do with multiple precision (gmp: libgmp10-dev) had to be installed.

**Comment by esden** [comment]
The requirements before building are listed in the README file. Will add stamps for unpacking and patching in the future to make the issue of not reading the README less painful in the future. Closing this issue for now. As this is mostly level 8 problem. :D
