### ISSUE TITLE
gdb has "moved". 

### ISSUE THREAD

**Issue by rewolff** [esden/summon-arm-toolchain#26]
In my case the script downloaded gdb-linaro-7.3-2011.10.tar.bz2 while it expects: gdb-7.3.1.tar.bz2 . 

I had to create a link to the source and a symlink to the build directory for it to build. ln -s gdb-linaro-7.3-2011.10 gdb-7.3.1

(and the cleanup then eventually deletes the symlink instead of the actual build directory).

**Comment by esden** [comment]
I think this should work now. And when compiling linaro the correct zip file should be used. If the issue still persists please let me know. :)
