### ISSUE TITLE
Missing armv4 blx compile option

### ISSUE THREAD

**Issue by OpenUAS** [esden/summon-arm-toolchain#32]
A BLX fix like this welcomed, see https://github.com/ReadyTalk/avian/pull/11, e.g. CHDK cannot be used by default with SAT toolchain

**Comment by esden** [comment]
I don't think sat's main goal is compiling for armv4 but if someone wants to provide a patch making this possible I am looking forward to that. (also check with the current version of sat if the problem still exists) Closing for now.
