### ISSUE TITLE
Error in server response: newlib-1.19.0.tar.gz

### ISSUE THREAD

**Issue by johnp789** [esden/summon-arm-toolchain#39]
When trying summon-arm-toolchain for the first time today, I ran into this: 

--2012-11-10 08:35:26--  ftp://sourceware.org/pub/newlib/newlib-1.19.0.tar.gz
  (try: 4) => `newlib-1.19.0.tar.gz'
Connecting to sourceware.org (sourceware.org)|209.132.180.131|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/newlib ... done.
==> SIZE newlib-1.19.0.tar.gz ... 14323667
==> PORT ... done.    ==> RETR newlib-1.19.0.tar.gz ... 
Error in server response, closing control connection.
Retrying.

**Comment by mlamoore** [comment]
I had the same issue when I erased summon-arm-toolchain and rebuilt it yesterday.

I went to that exact location in Firefox and was able to manually download the file and put it in summon-arm-toolchain/sources with the other downloads; once I put it there myself, re-running summon-arm-toolchain saw it as already downloaded and skipped it.

**Comment by chrysn** [comment]
for me, removing the --no-passive-ftp option in the fetch routine worked. don't they have an http mirror? usually i'd suggest using the pretty reliable debian mirrors, but the latest version is not packaged yet.

**Comment by Poofjunior** [comment]
Good call chrysn!  I also removed --no-passive-ftp from summon-arm-toolchain script, and I can now proceed with the download!

**Comment by esden** [comment]
I think this is fixed now. The --no-passive-ftp option is disabled by default now. Can be enabeled in the script using a variable.
