### ISSUE TITLE
remove --no-passive-ftp option to wget

### ISSUE THREAD

**Issue by akohlsmith** [esden/summon-arm-toolchain#43]
I'm not sure why that option is in there because there are far more people behind NATting firewalls than not, but I could not pull the archives down until I removed that option from the wget invocation in the script.

**Comment by residentsummer** [comment]
I confirm this issue - removing mentioned option helped to download newlib through ftp.

Thanks for the tip, @akohlsmith!

**Comment by esden** [comment]
We have variables for setting and unsetting this option now. Fixed. :)
