### ISSUE TITLE
Can not fetch newlib using active FTP mode

### ISSUE THREAD

**Issue by vsaw** [esden/summon-arm-toolchain#6]
Hello,

I had problem fetching the newlib library when the '--no-passive-ftp' flag was set.
Using 'wget' without that option worked like a charm.

Kind Regards,
Valentin

**Comment by esden** [comment]
No passive ftp forces wget to use active ftp. This is normally the more robust mode as it does not work with some firewall/proxy settings. Maybe having an alternative download page that is reachable over http would be an alternative?

Suggestions?

**Comment by markusg26** [comment]
The man page of wget suggests that "_passive ftp mode has a better chance of working_". And users where it doesn't work have probably already encountered it before and changed to active ftp using the wgetrc file.
So I would suggest to stick with the wget default of passive ftp.
Alternatively one could first try passive and then active ftp by using the _--timeout_ option of wget.

quote of the wget man page:

> If the machine is connected to the Internet directly, both passive
> and active FTP should work equally well.  Behind most firewall and
> NAT configurations passive FTP has a better chance of working.
> However, in some rare firewall configurations, active FTP actually
> works when passive FTP doesn't.  If you suspect this to be the
> case, use this option, or set "passive_ftp=off" in your init file.

**Comment by twaldecker** [comment]
I also had this issue. I ended manually downloading the file with a wget command and add the stamp file.

**Comment by benemorius** [comment]
There seems to have been some confusion as to which mode is more robust. Passive mode is better suited to today's internet and is the more robust option.

Active FTP requires that the client open a listening port for the data connection from the server and was never meant to work with NAT. It will always fail if the client is behind NAT except in the (rather common, but not common enough) case where the NAT device snoops the FTP traffic and parses the PORT command to know it needs to open an additional forwarded port to the client. This sounds like a dirty solution and indeed it is.

Passive FTP removes the need for an incoming connection on the client by allowing the client to initiate both the command and data connections to a listening server. This requires that the server's firewall is configured to accept the extra (data) connection, but it is a rare exception when a server admin fails to do so. I can confirm that all FTP servers which SAT connects to are properly configured as I have disabled active mode and run the script successfully from start to finish.

So while active FTP will fail in all cases where NAT is used without a dirty workaround for active FTP, passive FTP will typically only fail in cases of server misconfiguration. Needless to say, active FTP will fail far more often than passive.

Therefore, please remove the --no-passive-ftp switch. It is affecting far more users than have been vocal about it. Google has revealed a number of blog posts and comments where a sed one-liner or equivalent is thrown in to "fix" the script before running it.

**Comment by esden** [comment]
We disabled no-passive-ftp option by default now ... it can be enabled in the script using a variable now. Fixed :)
