### ISSUE TITLE
arm-none-eabi-gcc: error: unrecognized command line option

### ISSUE THREAD

**Issue by Bahkao** [esden/summon-arm-toolchain#61]
Hi everyone,
I need your help please. When i tried to execute some application with stm32_femto target i got many error and i don't k how to resolve those error.

mustafa@mustafa:~/stage/tinyosonstm32-code/apps/Blink$ make ggm_cortex
mkdir -p build/ggm_cortex
    compiling BlinkAppC to a ggm_cortex binary
ncc -o build/ggm_cortex/main.exe -O0 -g /home/mustafa/stage/tinyosonstm32-code/tos/chips/stm32/syscalls.c -Wall -Wshadow -Wnesc-all -target=ggm_cortex -fnesc-cfile=build/ggm_cortex/app.c -board= -L/home/mustafa/stage/tinyosonstm32-code/tos/platforms/ggm_cortex/vectors -L/home/mustafa/stage/tinyosonstm32-code/tos/platforms/ggm_cortex -L/home/mustafa/sat/arm-none-eabi/lib/thumb/cortex-m3  -DDEFINED_TOS_AM_GROUP=0x22 -DIDENT_APPNAME=\"BlinkAppC\" -DIDENT_USERNAME=\"mustafa\" -DIDENT_HOSTNAME=\"mustafa\" -DIDENT_USERHASH=0xf1ceecd8L -DIDENT_TIMESTAMP=0x54ff5540L -DIDENT_UIDHASH=0xc649ccd3L -DTINYOS -DSTM32 -T/home/mustafa/stage/tinyosonstm32-code/tos/chips/stm32/cortex.ld -DSTM32F1 -O0 -g -Wall  -fno-common  -mcpu=cortex-m3 -mthumb -msoft-float -MD -DSTM32F1 \
BlinkAppC.nc -lm -lc -lnosys -lopencm3_stm32f1 -I/home/mustafa/stage/tinyosonstm32-code/tos/platforms/ggm_cortex  -I/home/mustafa/sat/arm-none-eabi/include -I/home/mustafa/sat/arm-none-eabi/include/libopencm3/stm32 -I/home/mustafa/sat/arm-none-eabi/include/libopencm3/stm32/f1 -L/home/mustafa/stage/tinyosonstm32-code/tos/platforms/ggm_cortex/vectors -L/home/mustafa/stage/tinyosonstm32-code/tos/platforms/ggm_cortex -L/home/mustafa/sat/arm-none-eabi/lib/thumb/cortex-m3  -nostartfiles -mthumb -mcpu=cortex-m3 -msoft-float  
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-gcc=arm-none-eabi-gcc'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-include=nesc_nx'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-include=tos'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-scheduler=TinySchedulerC,TinySchedulerC.TaskBasic,TaskBasic,TaskBasic,runTask,postTask'
arm-none-eabi-gcc: error: unrecognized command line option '-_Wnesc-all'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-cfile=build/ggm_cortex/app.c'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-target=env'
arm-none-eabi-gcc: error: unrecognized command line option '-_fnesc-no-debug'
make: **\* [exe0] Error 1
Best regards

**Comment by esden** [comment]
Please consider using https://launchpad.net/gcc-arm-embedded instead. As described in the README on the main page of the repository.

summon-arm-toolchain is not maintained any more.
