### ISSUE TITLE
Issue building openocd

### ISSUE THREAD

**Issue by munk** [esden/summon-arm-toolchain#8]
I'm running summon-arm-toolchain on OSX 10.5.8.  After while, when configuring openocd-master, I get an error that says:  Error: Unknown option --rlink

grep tells me that there is no --rlink anywhere in the files in the directory tree, only --enable-rlink.  I've pasted the relevant messages below.  Any ideas on how to address this?  I don't need support for the Raisonance RLink JTAG programmer, so I'd be ok removing this option, but I don't see where to do it.  Thank you for your help!

---
- Configuring openocd-master
  ******************************************************************
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes

**_snip**_

=== configuring in jimtcl (/Users/jdowns/gcc-arm/esden-summon-arm-toolchain-280d1ac/build/jimtcl)
configure: running /bin/sh ../../openocd-master/jimtcl/configure.gnu '--prefix=/Users/jdowns/sat'  '--enable-maintainer-mode' '--enable-dummy' '--enable-ft2232_libftdi' '--enable-usb_blaster_libftdi' '--enable-ep93xx' '--enable-at91rm9200' '--enable-presto_libftdi' '--enable-usbprog' '--enable-jlink' '--enable-vsllink' '--enable-rlink' '--enable-arm-jtag-ew' 'CFLAGS= -I/opt/mine/include -I/opt/local/include' 'LDFLAGS= -L/opt/mine/lib -L/opt/local/lib' --cache-file=/dev/null --srcdir=../../openocd-master/jimtcl
Host System...i386-apple-darwin9.8.0
Build System...i386-apple-darwin9.8.0
C compiler... cc  -I/opt/mine/include -I/opt/local/include
C++ compiler... c++  -I/opt/mine/include -I/opt/local/include
Build C compiler...cc
Checking for stdlib.h...ok
Error: Unknown option --rlink
Try: 'configure --help' for options
configure: error: ../../openocd-master/jimtcl/configure.gnu failed for jimtcl

**Comment by aogail** [comment]
I am hitting this issue, also, on 10.7.2.

**Comment by doceme** [comment]
I saw this issue when trying to build openocd with [Homebrew](http://mxcl.github.com/homebrew) on 10.6.8.  I had to add the "--disable-option-checking" option to ./configure command.  I'm not sure if this will fix your problem or if it is the "right" way to fix it.

**Comment by aogail** [comment]
That got me past the failure. Thanks doceme!

**Comment by logic** [comment]
Same problem here, using current [homebrew](https://github.com/mxcl/homebrew/) on OSX 10.6.8. `--disable-option-checking` added to the openocd configure command line worked like a champ here as well.

**Comment by bchallenor** [comment]
`--disable-option-checking` works for me on 10.7.2, thanks.

**Comment by esden** [comment]
I think this works now. If not please open a new issue. :)
