### ISSUE TITLE
SVC is not permitted on this architecture

### ISSUE THREAD

**Issue by johnhowe** [esden/summon-arm-toolchain#9]
I get the following error
`/tmp/ccsk2KvI.s: Assembler messages:
 /tmp/ccsk2KvI.s:163: Error: SVC is not permitted on this architecture`
which appears to be a bug introduced into binutils as discussed here http://sourceware.org/bugzilla/show_bug.cgi?id=12296

I had to instead use binutils-2.20.1 for this script to work.

**Comment by esden** [comment]
Hi thanks for reporting this bug. Do you think we should add the patch to binutils to solve the problem instead of downgrading to a previous version of binutils?

Cheers Esden

**Comment by johnhowe** [comment]
I suppose it would be better to be using the current binutils, however I don't understand the system well enough to apply the fix myself and it was a no brainer to modify your script to use the older binutils version. It is your decision what you think is best. 
I appreciate the work you have done here. Thanks

**Comment by nullsub** [comment]
I still have this issue. What is an easy fix for this?

**Comment by johnhowe** [comment]
``` diff
diff --git a/summon-arm-toolchain b/summon-arm-toolchain
index 705b9cc..492551f 100755
--- a/summon-arm-toolchain
+++ b/summon-arm-toolchain
@@ -116,7 +116,7 @@ else
        GCCURL=http://launchpad.net/gcc-linaro/4.5/${GCCRELEASE}/+download/${GCC}.tar.bz2
 fi
-BINUTILS=binutils-2.21.1
+BINUTILS=binutils-2.20.1
 NEWLIB=newlib-1.19.0
 GDB=gdb-7.3.1
 OOCD=master
```

**Comment by nullsub** [comment]
It worked. Thank you

**Comment by johnhowe** [comment]
Fixed thanks to pieterg.

https://github.com/esden/summon-arm-toolchain/pull/10
